Complete till navbar
KBhautik6/Adorn-UI pull request #10
Opened 2024-01-16 14:16 UTC by KBhautik6

<img width="1280" alt="Screenshot 2024-01-15 at 10 28 01 AM" src="https://github.com/KBhautik6/Adorn-UI/assets/153491994/f20e4bed-ac9d-4185-84a6-7c04af723da4">

 - [x] Checking the code is duplicate or not?
 - [x] Is these code has bug
 - [ ] Is code is check by ankit sir or tara ma'am ?
 - [ ] Are you going to merge this or not?

2024-01-17 06:19 UTC, tarakhant1297 requested changes

2024-01-17 06:19 UTC, tarakhant1297 commented on src/stories/Navbar/Navbar.stories.js
> +        <h2>Adorn Box</h2>
@KBhautik6 use typography

2024-01-17 06:19 UTC, tarakhant1297 commented on src/stories/Navbar/Navbar.stories.js
> +            <StyledNavbarSearch
@KBhautik6 use input component with prefix search icon

2024-01-17 06:19 UTC, tarakhant1297 commented on src/theme.js
> +<<<<<<< HEAD
@KBhautik6 remove this

2024-01-17 06:22 UTC, KBhautik6 commented on src/stories/Navbar/Navbar.stories.js
> +        <h2>Adorn Box</h2>
okay ma'am

2024-01-17 06:22 UTC, KBhautik6 commented on src/stories/Navbar/Navbar.stories.js
> +            <StyledNavbarSearch
okay ma'am

2024-01-17 06:22 UTC, KBhautik6 commented on src/theme.js
> +<<<<<<< HEAD
okay ma'am

2024-01-17 12:01 UTC, tarakhant1297 requested changes

2024-01-17 12:01 UTC, tarakhant1297 commented on src/stories/Navbar/Navbar.stories.js
> +import Button from "../Button/Button";
@KBhautik6 import Button from "../Button"; import must point to index file

2024-01-17 12:01 UTC, tarakhant1297 commented on src/stories/Navbar/Navbar.stories.js
> +import Typography from "../Typography/Typography";
@KBhautik6 same same above 
import Badges from "../Badges/Badges";
import Typography from "../Typography/Typography";

2024-01-19 14:11 UTC, tarakhant1297 approved these changes

2024-01-22 04:59 UTC, ankitadrixus08 approved these changes

2024-03-05 05:39 UTC, merged