Complete the alert
KBhautik6/Adorn-UI pull request #3
Opened 2023-12-20 09:24 UTC by KBhautik6

### alerts
<img width="1280" alt="Screenshot 2023-12-20 at 2 41 23 PM" src="https://github.com/KBhautik6/Adorn-UI/assets/153491994/fb113091-4e2f-475b-a06b-c6078270490f">

### outline alert

<img width="1280" alt="Screenshot 2023-12-20 at 2 41 27 PM" src="https://github.com/KBhautik6/Adorn-UI/assets/153491994/31adea41-1499-4cb1-89e7-697d773e4842">

- [x] Checking the code is duplicate or not?
- [x] Is these code has bug 
- [ ] Is code is check by shubhum sir or ankit sir?
- [ ] Are you going to merge this or not?

2023-12-25 12:24 UTC, shubham-spreadd commented
@KBhautik6 please check component alignments

2023-12-25 12:26 UTC, shubham-spreadd requested changes

2023-12-25 12:26 UTC, shubham-spreadd commented on src/stories/Alert.js
> +    ishover={ishover}
isHover, border & outline should be managed by variant

2023-12-25 12:26 UTC, shubham-spreadd commented on src/theme.js
> +    white: "#f6f9fc",
remove redundant suffix & unused colors

2023-12-26 07:10 UTC, tarakhant1297 requested changes

2023-12-26 07:10 UTC, tarakhant1297 commented on README.TXT
@KBhautik6 remove this empty file

2023-12-26 07:10 UTC, tarakhant1297 commented on src/stories/Alert/Alert.Styled.js
> +    color: ${isoutline ? theme?.[type] : "white"};
@KBhautik6 read color from theme

2023-12-26 07:10 UTC, tarakhant1297 commented on src/stories/Alert/Alert.js
> +export const SimpleAlert = ({
@KBhautik6 file name and const should be same

2023-12-26 07:10 UTC, tarakhant1297 commented on src/stories/Alert/Alert.js
> +    isoutline={isoutline}
@KBhautik6 isoutline rename to `isOutline `

2023-12-26 07:10 UTC, tarakhant1297 commented on src/stories/Alert/Alert.js
> +    ishover={ishover}
@KBhautik6 we don't need to pass this props we manage using  css

2023-12-26 07:10 UTC, tarakhant1297 commented on src/stories/Alert/Alert.stories.js
> +      variant="outlined"
@KBhautik6 why you pass isoutline flag as we pass varinat="outlined"

2023-12-26 07:18 UTC, KBhautik6 commented on src/stories/Alert/Alert.js
> +    isoutline={isoutline}
okay

2023-12-27 05:39 UTC, tarakhant1297 approved these changes

2023-12-27 05:39 UTC, tarakhant1297 commented on src/stories/Alert/Alert.Styled.js
> +export const Alert = styled.button`
@KBhautik6 add styled prefix

2023-12-27 06:06 UTC, merged