Complete of avatar
KBhautik6/Adorn-UI pull request #4
Opened 2023-12-20 12:08 UTC by KBhautik6

### Square profile

<img width="1280" alt="Screenshot 2023-12-20 at 5 34 02 PM" src="https://github.com/KBhautik6/Adorn-UI/assets/153491994/2a703df7-2d96-46df-a10e-b4504429808b">

### Circle profile

<img width="1280" alt="Screenshot 2023-12-20 at 5 34 08 PM" src="https://github.com/KBhautik6/Adorn-UI/assets/153491994/39cf8e2f-9f55-4b05-a124-932d29784b72">

- [x] Checking the code is duplicate or not?
- [x] Is these code has bug 
- [ ] Is code is check by shubhum sir or ankit sir?
- [ ] Are you going to merge this or not?

2023-12-25 12:27 UTC, shubham-spreadd approved these changes

2023-12-25 12:27 UTC, shubham-spreadd requested changes

2023-12-25 12:27 UTC, shubham-spreadd commented on src/stories/Avatar.stories.js
> +  </AvatarContainer>
props should be similar to antd

2023-12-27 06:28 UTC, KBhautik6 commented on src/stories/Avatar.stories.js
> +  </AvatarContainer>
Okay

2023-12-27 11:07 UTC, ankitadrixus08 approved these changes

2023-12-27 11:20 UTC, tarakhant1297 requested changes

2023-12-27 11:20 UTC, tarakhant1297 commented on src/stories/Avatar.Styled.js
> +export const DisplayImage = styled.img`
@KBhautik6 add styled prefix

2023-12-27 11:26 UTC, KBhautik6 commented on src/stories/Avatar.Styled.js
> +export const DisplayImage = styled.img`
Done

2023-12-27 13:48 UTC, merged