Complete the Badges
KBhautik6/Adorn-UI pull request #5
Opened 2023-12-27 10:22 UTC by KBhautik6

- [x] Checking the code is duplicate or not?
- [x] Is these code has bug 
- [ ] Is code is check by shubhum sir or ankit sir or tara ma'am?
- [ ] Are you going to merge this or not?

2023-12-27 11:21 UTC, tarakhant1297 requested changes

2023-12-27 11:21 UTC, tarakhant1297 commented on src/stories/Badges/Badges.js
> +export const Badges = ({ src, size, varaint, colortype, text }) => {
@KBhautik6 re to name colortype color

2023-12-27 11:21 UTC, tarakhant1297 commented on src/stories/Badges/Badges.styled.js
> +  /* border-color: ${theme?.white}; */
@KBhautik6 remove commented code

2023-12-27 11:37 UTC, KBhautik6 commented on src/stories/Badges/Badges.styled.js
> +  /* border-color: ${theme?.white}; */
okay

2023-12-27 11:37 UTC, KBhautik6 commented on src/stories/Badges/Badges.js
> +export const Badges = ({ src, size, varaint, colortype, text }) => {
Okay i will do color

2023-12-28 07:04 UTC, ankitadrixus08 commented on src/stories/Badges/Badges.styled.js
> +  border: 2px solid;
use color from theme @KBhautik6

2023-12-28 07:04 UTC, ankitadrixus08 commented on src/stories/Badges/Badges.styled.js
> +  border-color: white;
use shorthand property @KBhautik6

2023-12-28 07:04 UTC, ankitadrixus08 commented on src/stories/Badges/Badges.styled.js
> +  color: white;
use color from theme @KBhautik6

2023-12-28 07:12 UTC, KBhautik6 commented on src/stories/Badges/Badges.styled.js
> +  border: 2px solid;
okay sir

2023-12-28 07:12 UTC, KBhautik6 commented on src/stories/Badges/Badges.styled.js
> +  border-color: white;
okay sir

2023-12-28 07:12 UTC, KBhautik6 commented on src/stories/Badges/Badges.styled.js
> +  color: white;
okay sir

2023-12-29 05:17 UTC, tarakhant1297 approved these changes

2023-12-29 05:21 UTC, ankitadrixus08 approved these changes

2023-12-29 05:22 UTC, merged