Complete the Toast component
KBhautik6/Adorn-UI pull request #6
Opened 2023-12-27 11:05 UTC by KBhautik6

### Toast section
<img width="1280" alt="Screenshot 2023-12-25 at 12 44 58 PM" src="https://github.com/KBhautik6/Adorn-UI/assets/153491994/80d5e6b9-b1d8-4353-8790-9a630afd7625">

- [x] Checking the code is duplicate or not?
- [x] Is these code has bug 
- [ ] Is code is check by shubhum sir or ankit sir or tara ma'am?
- [ ] Are you going to merge this or not?

2023-12-27 11:22 UTC, tarakhant1297 requested changes

2023-12-27 11:22 UTC, tarakhant1297 commented on src/stories/Toast.js
> +    <StyledText colortype={colortype}>
@KBhautik6 rename colortype to color

2023-12-28 07:04 UTC, ankitadrixus08 commented on src/stories/Toast.styled.js
> +    border:2px solid;
use shorthand property here @KBhautik6

2023-12-28 07:05 UTC, KBhautik6 commented on src/stories/Toast.js
> +    <StyledText colortype={colortype}>
okay

2023-12-28 07:05 UTC, KBhautik6 commented on src/stories/Toast.styled.js
> +    border:2px solid;
okay

2023-12-29 05:21 UTC, ankitadrixus08 approved these changes

2023-12-29 05:23 UTC, tarakhant1297 approved these changes

2023-12-29 06:01 UTC, merged