Complete the Images
KBhautik6/Adorn-UI pull request #7
Opened 2023-12-28 12:10 UTC by KBhautik6

- [ ] Checking the code is duplicate or not?
 - [ ] Is these code has bug
 - [ ] ]Is code is check by shubhum sir or ankit sir?

2023-12-29 05:21 UTC, ankitadrixus08 approved these changes

2023-12-29 05:22 UTC, tarakhant1297 requested changes

2023-12-29 05:22 UTC, tarakhant1297 commented on src/Image/Image.styled.js
> +export const StyledImage = styled.img`
@KBhautik6 refactor this code

2023-12-29 05:51 UTC, KBhautik6 commented on src/Image/Image.styled.js
> +export const StyledImage = styled.img`
okay

2024-01-01 07:13 UTC, tarakhant1297 requested changes

2024-01-01 07:13 UTC, tarakhant1297 commented on src/stories/Image/Image.styled.js
> +const size = {
@KBhautik6 put in size const file

2024-01-01 07:13 UTC, tarakhant1297 commented on src/stories/Image/Image.styled.js
> +    shape === "response" &&
@KBhautik6 why you add this `response ` shape

2024-01-01 07:29 UTC, KBhautik6 commented on src/stories/Image/Image.styled.js
> +const size = {
okay

2024-01-01 07:37 UTC, KBhautik6 commented on src/stories/Image/Image.styled.js
> +    shape === "response" &&
Okay i will change the shape naming conventation with different name

2024-01-02 06:25 UTC, tarakhant1297 requested changes

2024-01-02 06:25 UTC, tarakhant1297 commented on src/Size.js
>  export const sizes = {
@KBhautik6 give proper name to each size const

2024-01-02 06:25 UTC, tarakhant1297 commented on src/stories/Image/Image.js
> +export const Images = ({ src, size, variant }) => {
@KBhautik6 file and component must be same why you add `Images `?

2024-01-05 05:27 UTC, tarakhant1297 approved these changes

2024-01-05 05:28 UTC, merged