Complete the Input
KBhautik6/Adorn-UI pull request #8
Opened 2023-12-29 06:36 UTC by KBhautik6

<img width="1280" alt="Screenshot 2023-12-29 at 12 05 17 PM" src="https://github.com/KBhautik6/Adorn-UI/assets/153491994/2db2cd97-83d4-4c1a-8840-cc734b036bd6">

 - [x] Checking the code is duplicate or not?
 - [x] Is these code has bug
 - [ ] Is code is check by shubhum sir or ankit sir or tara ma'am?
 - [ ] Are you going to merge this or not?

2024-01-01 07:14 UTC, tarakhant1297 requested changes
https://ant.design/components/input follow this for input

2024-01-17 05:49 UTC, tarakhant1297 requested changes

2024-01-17 05:49 UTC, tarakhant1297 commented on src/stories/Input/Input.js
> +export const Input = ({ type,id,placehold,prefix,suffix, }) => {
@KBhautik6 give proper spacing in props and `placehold ` rename to `placeholder`

2024-01-17 05:53 UTC, KBhautik6 commented on src/stories/Input/Input.js
> +export const Input = ({ type,id,placehold,prefix,suffix, }) => {
okay ma'am i will do it

2024-01-17 06:20 UTC, tarakhant1297 approved these changes

2024-01-17 06:24 UTC, merged